"""books table

Revision ID: 5cf5d8878c7c
Revises: 90a58a51dd70
Create Date: 2022-01-09 18:46:24.004731

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5cf5d8878c7c'
down_revision = '90a58a51dd70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('number_of_pages', sa.Integer(), nullable=False))
    op.drop_column('books', 'number_of_pager')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('number_of_pager', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('books', 'number_of_pages')
    # ### end Alembic commands ###
